# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c4d7b9da6f2e1b8d3677f1322f20a891fedc3786ebd885885152f7a739f62348b0f1fdb16583139423b6ba8075aaa5171ae35c2e2d956724797473aba2bbf04

test:
  secret_key_base: 3b0f67eca13538652006ded53595635c77f99c7f50371ccf3aab7f48cfc752c75b266831f120b3b4c719172cb88bf399130582a3f0d2a781d3b59a97d0c1aa75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
